### ISSUE TITLE
Clean Up of the NonElectrical Package

### ISSUE THREAD

**Issue by MaximeBaudette** [itesla/ipsl#12]
As of today the **NonElectrical** package is badly organized and very redundant. The block's name are difficult to read, and it is hard to find exactly the block one is looking for. 
We should discuss:
- A clearer naming convention
- The structure of the package (Math, Logical, Continuous, NonLinear, Functions), maybe remove Continuous and NonLinear?
- Rewrite the blocks with saturation (dig into windup/Non-windup)

![image](https://cloud.githubusercontent.com/assets/15156063/11014937/de0d2f56-854a-11e5-9493-4a857059a98c.png)
![image](https://cloud.githubusercontent.com/assets/15156063/11014939/eb45ec80-854a-11e5-925e-f4a0eadbfc60.png)

**Comment by tinrabuzin** [comment]
###### Updates on this issue.

So, what you see in the photo above is from the IEEE Std. 421.5 Annex E which describes how the transfer functions should be implemented with the anti wind-up limits. 

A lot of the tfs with anti windup limits are already implemented but, as you know, it's a mess because there are more implementation for each tf. Some tfs, in all of their implementations (e.g. LeadLag filter) do not behave as they should according to the standard which is probably why I couldn't validate some of the excitation system I was making. 

Anyway, I will go through every single one of them, make them compliant with the standard and then update the control models with the new functions. The standard is, I believe, used by PSS/E as well but it is unclear for some tfs (e.g. LeadLag) when I try to read it.

This process might take a while.

**Comment by dietmarw** [comment]
@tinrabuzin When going through the library I'd advice to remove all those standard blocks that are also available in the MSL providing the exact same functionality (but sometimes better implemented). Example: `iPSL.NonElectrical.Math.Min` can be removed and `Modelica.Blocks.Math.Min` used instead. Just to name one. There are plenty more. And over time it would be easier to maintain if code duplication is avoided. 

I also noticed that the naming convention wrt to connectors can be improved. Blocks have normally inputs called "u" and outputs "y" and not "p" and "n" which does not make sense for in/output connectors.

**Comment by tinrabuzin** [comment]
@dietmarw I'm already on it. If you check the TransferFunctions branch you can see that I did remove a lot of the Math blocks. For the rest I have to check if there is a specific function that cannot be done with MSL. 

I also started improving the blocks by extending the SISO from the MSL so the standard naming is on the way.

I'd appreciate if you have a suggestion for our problem that I was talking about in the previous comment. We use a lot of, e.g., lead-lag filters and first order derivative transfer functions in our library whose action can be (in the reference software) omitted by setting the time constants to be equal in case of lead lag or to 0 in case of first order derivative. This causes some errors if we use the blocks from MSL and that's why, currently, we need to have some of them in our library. Also, we are using some of them with the anti windup limits which is not supported in the MSL (except for the integrator). I was trying to figure out if all of this can be done somehow with the blocks from MSL but I couldn't find it. Do you know if that's possible?

**Comment by dietmarw** [comment]
@tinrabuzin If you could give me one explicit example I could look at it. But I have unfortunately not the time currently (I wish I had) to go through the library.

**Comment by tinrabuzin** [comment]
@dietmarw 
Hi! I prepared a small model that shows the difference between the behaviour we want and the best behaviour I can achieve with the models from MSL (see the link below). You can simulate it for 20s to see the difference between the output from the limiter and the output from the simple lag. As I mentioned in the previous comment, the problem is the anti windup limiter that, as far as I can see, is not available in the MSL. 

https://www.dropbox.com/s/p49g19xsmqp9dox/TfExample.mo?dl=0

**Comment by lvanfretti** [comment]
@tinrabuzin regarding these sort of block

**Comment by dietmarw** [comment]
@tinrabuzin I'm a little confused. Looking at your example you show that you **can** get the same behaviour with the combination of the two blocks. So why not simply create a new block model that simple contains the two MSL blocks and add the parameters.

I've extended your example with such a model including the updated test. But I'm not sure I've understood the problem correctly.
https://dl.dropboxusercontent.com/u/151762/TfExample.mo

**Comment by tinrabuzin** [comment]
This is how my screen looks like: 
<img width="1152" alt="screen shot 2015-11-27 at 12 53 52" src="https://cloud.githubusercontent.com/assets/13916934/11440826/15192976-9506-11e5-8c83-be2b48eac3c1.png">

As you can see the outputs are not the same.

**Comment by dietmarw** [comment]
Ah I didn't simulate long enough ;-) Let me check again.

**Comment by dietmarw** [comment]
OK so you could get the similar behaviour using `Modelica.Blocks.Continuous.LimPID` in PD mode but in this case it's probably not worth it. One thing though you could improve is to convert the `model`s to `block`s because that's what they are.
