### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by NathyGuam** [itesla/ipsl#180]
Good morning
I am modeling a power system, but I have a problem, I create the file as a package but this one is not created or displayed, same as the generator group, the same is not created the package although the package icon appears in the File address is only the name of the package, but not the package (39bus.mo) and does not appear (package.mo).
Someone who can help me please, since your information will be very helpful.
Thank you very much.

**Comment by machadosaia** [comment]
Good morning @NathyGuam ,

Modelica does not accept model names starting by a number so we recommend you to change `39bus` by an accepted model name, for example `bus39`.
After that you should do two things:

1.  Create the file  `package.mo` (if we have understood you well, you have already done it).

2. Add the `bus39` to the file `package.order`.

Regards.

**Comment by NathyGuam** [comment]
Sorry if I create the file with the name of IEEE39 and design with all the elements, but I do not know how to create the package that is needed to open the file because I just click the file (IEEE39) and the file is opened The correct thing is to go to the package first to load the file directly, it's a thesis project that I'm doing.
Please if you can help me with that problem

**Comment by machadosaia** [comment]
If you want to create the model **IEEE39** inside a package named, for example, **IEEE** you should do the following steps:

a.Create a folder name **IEEE**.

b.Inside this folder create the following three files:

b.1.**package.order** containing the following line:

`IEEE39`

b.2.**package.mo** containing the following:
`within ;
package IEEE
end IEEE;`

b.3.**IEEE39.mo** containing all its elements. The first line should be `within IEEE;` because it is inside this package.

Doing that and opening the package.mo with OpenModelica you will see that:

![image](https://cloud.githubusercontent.com/assets/22952804/25485316/d5a8246e-2b5d-11e7-9165-4dbc4486fe16.png)

Finally if you want to add this to the iPSL library, for example, inside iPSL/Examples you should update the following files:

1. Add the folder **IEEE** created in the previous process inside the folder iPSL/Examples.

2. iPSL/Examples/package.order: add the line `IEEE`

3. iPSL/Examples/IEEE/package.mo: update the first line to `within iPSL.Examples;`

4. iPSL/Examples/IEEE/IEEE39.mo: update the first line to: `within iPSL.Examples.IEEE;`

Doing that and opening with OpenModelica the iPSL you will see that:

![image](https://cloud.githubusercontent.com/assets/22952804/25485506/75d3eb30-2b5e-11e7-9d8f-b419f0fa9448.png)

**Comment by NathyGuam** [comment]
good morning
Already create those files but I do not have the packages of IEEE39 and also the package of Generation_Groups, in addition the icons of the groupbus at the moment of dragging them to the sheet to insert I get a message like this: The model GroupBus1 is defined as partial.
The component will be added as a replaceable component.
Thanks for the help and sorry for the inconvenience

[archivo.docx](https://github.com/itesla/ipsl/files/964332/archivo.docx)

**Comment by viruezr** [comment]
Sorry @NathyGuam we do not completely understand your issue. In Modelica website you can find more information about how to create libraries, packages and models.

**Comment by NathyGuam** [comment]
Diseñe un modelo eléctrico, para el cual se hace necesario abrirlo con un package, sin embargo al momento de crear mi package no se genera o no se si tal ves hay que hacerlo individualmente, mi package se llama IEEE39, dentro de este esta el modelo IEEE_39_buses, para el cual también hay que generar un package para el uso/ingreso de generadores los mismos que se me aparecen como solo un punto hablando gráficamente, puesto que en el ejemplo de IEEE9 e IEEE14 barras son iconos de generadores.
Por favor si alguien me puede ayudar quedare muy agradecida.

**Comment by NathyGuam** [comment]
Good afternoon
please if you can help me, design a system of 39 bars but when placing the controllers the system does not compile, I am using the PSL type 4 generator of PSAT please if someone suggests that AVR use. The information they give me will be very valuable.

**Comment by NathyGuam** [comment]
Good afternoon
please if you can help me, design a system of 39 bars but when placing the controllers the system does not compile, I am using the PSL type 4 generator of PSAT please if someone suggests that AVR use. The information they give me will be very valuable.

**Comment by petitrenaudseb** [comment]
Good Morning @NathyGuam 
Which kind of AVR do you use ?
Have you try tro compile your system with set point instead of AVR ?

**Comment by NathyGuam** [comment]
GOOD MORNING I am using this IPSL/Electrical/Controls/PSAT/AVR/AvrtipeII and please could you tell me what it is or how do I do the Set point ?

**Comment by petitrenaudseb** [comment]
You only have to replace your AVR by a constant (fixed value, equivalent to a set point)

**Comment by NathyGuam** [comment]
[AVR.docx](https://github.com/itesla/ipsl/files/1487738/AVR.docx)
THE WAY OF CONNECTION AS YOU SEE THIS IS NOT OK?
