### ISSUE TITLE
PSS2A type of some parameters

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#33]
In model IPSL.Electrical.Control.PSS.PSS2A.PSS2A:

1- In the dyr file of REN System, the parameters M and N in the dyr file (PSS/E) are integer but when iTesla module put them in the DDB they are converted into real values. Otherwise in the Modelica model they are integers. ¿Could you define these parameters as Real values in the model?

2- In the dyr file of REN Systems the parameters T_w4 and T_w2 are 0 but in the Modelica model they should be non-zero. In Trello, @tinrabuzin  recommended the following: 

```
"For the ImSimpleLag you can put T_6 to 1e-10, and for the washout you can set T_w2 to 1e-10."
```

For the proper simulation of REN system we need to know if the behaviour of ESST1A  will be equal to the expected in PSS/E with T_w2 = 0 and T_w4=0. 
(From PSS/E Manual:
Washouts:
To bypass second washout, first signal: set Tw2 = 0
To bypass second washout, second signal: set Tw4 = 0)

Thank you.

AIA team.

**Comment by tinrabuzin** [comment]
@AIAitesla So, I updated the PSS2A model to have Real instead of Integer values for parameters M and N. However, there a ramp tracking filter that uses these parameters is not included in the model so, unless you use M=N=0, you won't get the same behaviour for PSS2A as in the PSSE. 

Also, I updated PSS2A and PSS2B to support the bypass of the washout filters. My comment about setting the time constants to 1e-10 from your second point is still valid.
