### ISSUE TITLE
Modelica (Dymola), GIT and Annotation Issue

### ISSUE THREAD

**Issue by MaximeBaudette** [itesla/ipsl#35]
We have a recurrent issue with the library that we develop almost all the time with Dymola and the GIT repository. 
The problem is that any minor modification in a single model results in changes in numerous models in their annotations, see Figure:
![image](https://cloud.githubusercontent.com/assets/15156063/11568244/5da320a4-99eb-11e5-9987-dd4f82aa0ed5.png)

The problem is that, there are so many of these modifications, it makes the work of making a clean commit so laborious that most of us just commit everything. This is moslty because we don't want to miss one of the real change we have implemented in the code. 

The endangers the readibility of the commits, and creates furthers issues when merging branches. 

@dietmarw Do you have any idea where this is coming from and how to fix that undesirable behaviour? 

Do you know if I can ping someone else to look into this issue.
This is a problem that we've had since the beginning, and wee tried different strategies for getting rid of it (several saving methods, etc.) but never manged to get rid of it

**Comment by dietmarw** [comment]
Unfortunately this is a long and ongoing problem. Dymola has actually becoming better (that means more predictable) in its heuristic rules on how to write out Modelica code over the years. In the latest release 2016FD01 they even started removing empty Dummy `__Dymola_*` annotations. Something that was/is a big annoyance and led me to write the `-c` option in my [ttws](https://github.com/dietmarw/trimtrailingwhitespaces) tool. 

OK so how to deal with it. The code written out by Dymola is different due to  the different (and hopefully more predictable) heuristic rules. In practice this  means that if you open a model that has been saved with an older version of Dymola or simply with a different tool or editor it will change upon save. Here some options:
1. From time to time, e.g., after a new release of Dymola, do a global rewrite of the whole library and commit this. Problem is here of course that you will be able to see the functional change  of a commit before that and after that "clean-up" commit but not when looking at a change across that commit. Also there is of course no guarantee that Dymola will still generate dummy changes by introducing new line shifts etc.
2. Use the power of your git tool. I personally use `git gui` (other tools might offer the same feature but I know that git gui is available on all platforms) because it lets me **see** the to be committed changes and in addition I can simply select the lines and hunks that should be committed (via right-click). That way I simply ignore the dummy changes of Dymola and reset the working copy after having committed the real changes. 
3. **Don't use Dymola editor for simple text edits.** This might sound cumbersome but is actually quite effective. When working on the MSL where I try to create **only** functional changes I do the real changes (as long as they are not connected with diagram layer or graphical edits) in my text editor of choice (emacs, but Atom.io has also very good (and [actively maintained](https://atom.io/packages/language-modelica)) Modelica support) save it and then run the test in Dymola by simply reloading the library via `File -> Version -> Refresh...` (short ALT+F V H). So I use Dymola to run the tests and do simple test edits there but don't actually save in Dymola but do the real save in my text editor. OMEdit has also become better in handling textedits. The latest nightly-build even lets you save illegal modelica code so you can continue later. Something that was not possible before (including the latest stable release 1.9.3) and you lost your changes when you closed/crashed (it happens) OMEdit.

**Comment by MaximeBaudette** [comment]
@dietmarw 
Thank you for your insight in the issue. Our main problem is however not between other editors and Dymola or even between an old version of Dymola and the current one, but between Dymola itself. I have requested everybody to upgrade their Dymola version to the latest one (2016). 
So far we haven't identified a coherent behavior of Dymola as to when it generates these annotation changes, but it seems that when GIT has been used to get a newer version (after pull), then it will happen for sure. 

The biggest issue with this is that, one modifications in one file can generate 50 annotation changes. And as soon as we modify more than one file (a typical batch of modification, implies working on several models at the same time), it's not rare that GIT will show 100 - 200 file modifications. There even using the GUI is too troublesome, so we just commit everything (I know I usually loose patience if I have to go through 10-20+ unnecessary annotation changes). 

We will now try by using the autoformatting option from Dymola, so we have shared the Dymola startup script that sets the auto-formatting on and max line length to 200, we have noticed it seemed to generate less garbage changes. 
And do you know where we can submit bug reports to Dymola? I browsed their website, but it seemed very obscure and I didn't find any way of doing it. This is very unsatisfying to me, cause I guess that without bug report, there is no chances of seeing this improved in the future. 

Best

**Comment by dietmarw** [comment]
> I have requested everybody to upgrade their Dymola version to the latest one (2016). 

The latest is 2016FD01 released about 2 weeks ago. You should contact your vendor or simply request the demo from the website which is identical with the full version given you have a valid license key.

> There even using the GUI is too troublesome,

This part I don't understand. You KNOW what model you are working on. So you know which file changes you **only** need to commit. So simply don't select the other changed files. The same goes for within the files. It might cost you 30 sec (literally) extra to review the changes that you need to pick but you gain so much out of this. Also you help others by not "wasting" their time when figuring out the changes.  After you committed your changes you simply do a `git reset --hard` and all is back to normal.

> And do you know where we can submit bug reports to Dymola?

DS has offloaded this to your local sales contact. Which is very frustrating as one can't even be sure that issues are handed up to DS. It all depends on your sales contact.

**Comment by dietmarw** [comment]
One thing that I forgot to mention is that unfortunately both 2016 and 2016FD01 now are so "kind" to introduce even more noise when you use the HTML editor (wysiwig). Dymola added support for CSS and this means it now marks all text passages you copy into that editor with a span and a font setting. :-(

**Comment by tbeu** [comment]
Does it help if the text is copied from a plain text editor like Notepad++ or UltraEdit instead?

**Comment by MaximeBaudette** [comment]
@tbeu From my own experience, I faced difficulties with pasting HTML code (for the annotations) into Dymola. It is manageable, but still very annoying that a simple copy-pasting generates issues with Dymola. 
I guess to avoid any issues, you would have to open the .mo file and edit it in Notepad++

@dietmarw 

> This part I don't understand. You KNOW what model you are working on. So you know which file changes you only need to commit. So simply don't select the other changed files. 

Actually this is were we have faced the most issues. We don't always know which files are modified, when implementing the changes, and it can be many at the same time. I perfectly understand that when modifying a single model one should do as you mention, and this is what we do, but as soon as we implement changes that have broad repercussions in the library, then sometimes we loose track of which files were modified, especially that other files are modified (package files). 
I recommended that people should commit their work before leaving work, to minimize the risk of loosing track of which files have been modified, but there still have been situations, where we still get lost in all these changes generated by Dymola, that screening 150 file modification is just to troublesome to make sure we don't forget any of the modified files. 

Anyhow, we will try to be better at managing this, applying your good practices :smiley:

**Comment by dietmarw** [comment]
I forgot to mention, what _should_ work is using an external HTML editor then copy the HTML **source** and paste that into the info **text** editor of Dymola. So long I have not noticed any other magic than replacing `"` with `\"` behind the scenes (and that part is rather useful).

**Comment by MaximeBaudette** [comment]
@dietmarw 
Actually I have faced issues with this manoeuvre as well... I provided several students some HTML code to paste in their models for information section, and Dymola found a way to break that HTML code. 
I can't explain why it happened, maybe some of the students copied the code and then modified the text in the wysiwyg editor, or something else... but the code got broken.

**Comment by dietmarw** [comment]
:-(
