### ISSUE TITLE
Modelica Package Manager

### ISSUE THREAD

**Issue by tinrabuzin** [itesla/ipsl#5]
http://impact.github.io/#/

Should we try to include the iPSL there? @MaximeBaudette

**Comment by lvanfretti** [comment]
Of course!

**Comment by dietmarw** [comment]
As soon as there is a release it will be picked up by impact :-)

**Comment by dietmarw** [comment]
Also have a read on [impact on library developers](https://github.com/impact/impact/blob/master/resources/docs/modelica2015/paper/impact.md#impact-on-library-developers) from our last Modelica conference paper.

**Comment by lvanfretti** [comment]
@tinrabuzin I think you can follow the instructions given by @dietmarw to comply with Impact.
@MaximeBaudette please notice the info that @dietmarw is providing on this.

**Comment by MaximeBaudette** [comment]
@tinrabuzin I will prepare the release

**Comment by MaximeBaudette** [comment]
@dietmarw 
Do you have any recommendation as to preparing a release of the library? 
In particular, I was thinking about the structure of the .mo file. For the purpose of the repository I introduced the broken down version of the library that sorts every packages in sub-folders and every models in single files. Therefore, I was wondering if it would be more suitable to re-save the library as a single .mo file containing everything for the "release" package. 
Any thoughts on that?

**Comment by dietmarw** [comment]
I think making the structure as modular as possible is the right way. So each model in its own file would be the right approach. This also means less merge conflicts and especially when people work with Dymola you can easily ignore dummy changes in files where you know you did not touch,

As for distribution I would not bother trying to repackage the whole library. [impact](https://github.com/impact/impact) for one does not care as it will simply pull down your released library in the directory (including the dependencies) and you are ready to go. 

You can try already now (despite #16, impact will actually fix your version to v0.8.0):
1. Download the self-contained static impact binary for your platform from https://github.com/impact/impact/releases and extract it to preferably a directory with your PATH
2. create a fresh working directory 
3. from inside that directory run `impact install iPSL`
4. Once impact has finished look at the contents of that directory (and now you might also understand why #8 needed to be fixed)

Otherwise if you want to make a traditional package available (including the "old" version number connected folder name - which impact does not care about, btw) then I suggest you:
- tag your master with the release version, e.g., `v0.8.0` (see also #16)
- take your master snapshot of that version and do some manual clean-ups (adding generated files like HTML help or other documents, removing test packages etc) and put it in folder `iPSL 0.8.0` and zip that one and attach it to the release (just like you've done). If you like to save as a single `.mo` be my guest but it normally makes it more awkward when you also ship Resources on the side (which is quite naturally) and you end up having several folders anyway.

**Comment by MaximeBaudette** [comment]
@dietmarw 
I initially closed that issue but realized that: 
- We appear on https://modelica.org/libraries
- We don't appear in http://impact.github.io/#/

Any idea why it is so? Did I miss a step in building the releases?

**Comment by dietmarw** [comment]
No, it's a problem on our side. We have to sync the indexes we are generating. But this time of year has been rather hectic. We hope to get that fixed after New Years.

**Comment by MaximeBaudette** [comment]
Ok then you don't mind if I close that issue :-)
