### ISSUE TITLE
Move copyright notice into "revisions" section?

### ISSUE THREAD

**Issue by dietmarw** [itesla/ipsl#62]
I noticed that you have the copyright notice present in all models in the "info" layer of the documentation. You might consider using the "revisions" layer instead for this purpose. This way it's easier to distinguish between real info and just default copyright and authors stamp. Quite a lot libraries do it this way but is of course not a must.

A step further would be to not have the copyright notice in all models in the development version but a simple place holder (e.g., `<!-- DISCLAIMER -->` which is legal HTML and will not cause HTML checker to complain :-) ) that gets replaced with an updated copyright notice before release. That way your source code does not have lots of duplicate code that needs to be updated with every release. Just an idea.

**Comment by MaximeBaudette** [comment]
For your first comment:
Yes why not, my first try was to put the copyright notice in the Modelica code as a comment, but this turned out to not work as expected. 
Then I thought about the information annotations, and nobody had objections, so we went for it.

For your second comment:
I see your point, but I guess it is a bit too fancy for now. We already have a hard time keeping up with other issues of the library.

**Comment by MaximeBaudette** [comment]
@dietmarw 
that closing was involuntary, I clicked the wrong button.

**Comment by MaximeBaudette** [comment]
Following the discussion in #7 , the license will be changed to MPL 2 if I'm not mistaken. 
When I update the license I will put it in the "revision" section
