### ISSUE TITLE
LGPL causes issues in combination with FMUs

### ISSUE THREAD

**Issue by dietmarw** [itesla/ipsl#7]
I noticed that your library is licensed under LGPL now there is an issue here since LGPL does not allow static linking with other non-lgpl code. This basically means you can not use your library in combination with any other library (including the MSL btw) if you generate an FMU that you like to distribute. There might be other cases. So you might wanna think of re-licensing under MPL which basically allows static linking but is otherwise similar to lgpl.  See also the section on this in our [impact paper at the last Modelica conference](https://github.com/impact/impact/blob/master/resources/docs/modelica2015/paper/impact.md#which-license-is-best-for-your-library).

**Comment by lvanfretti** [comment]
@itesla I thought that our colleagues (Eric) had checked which license was the most appropriate?

@dietmarw 'edit' I will ask the project partners about this issue. I'll see what I can do, but no promises.

**Comment by itesla** [comment]
@lvanfretti Yes he had. I forward him this issue.

**Comment by jbheyberger** [comment]
@dietmarw Thank you for rising this issue. We will address your question in the next project meeting and we will give you feedback on the agreed solution.

**Comment by lvanfretti** [comment]
@dietmarw so that you know, I am not representing the iTesla project here, just representing myself (I guess). Thus, I have edited my previous comment as I can't speak on behalf of the project. The issue you raise will indeed affect me anyway, so I do hope I can try to discuss it with my project colleagues in a few weeks during a project meeting. So, thank you for the information.

You will get feedback from @jbheyberger, @geofjamg or @itesla who are from RTE and are taking care of the management of the repository on the iTesla project behalf. So that you know who to address if you have any further issues to raise on this matter.

**Comment by MaximeBaudette** [comment]
@lvanfretti @fran-jo don't forget to bring up this during the meeting tomorrow

**Comment by MaximeBaudette** [comment]
@fran-jo told me that an agreement was met on using the MPL license.
I will implement it for the release scheduled in the end of January.
