### ISSUE TITLE
Documentation of models

### ISSUE THREAD

**Issue by dietmarw** [itesla/ipsl#9]
Looking at he iPSL as it could do with some more documentation and a "User's Guide"

**Comment by lvanfretti** [comment]
@dietmarw me and @tinrabuzin are working on an "application guide" and we have some teaching material we use at workshops.

Regarding documentation, we can add some links to material in my student's thesis, etc; but it will take sometime to clean up all the test models and examples, as different students were developing using older versions of the lib.., and because we were not using GIT at the beginning which made a mess... it was not their fault, it's my fault.

Anyway, @tinrabuzin is working on this, @dietmarw maybe you can follow [this issue](https://github.com/itesla/ipsl/issues/4) and give some feedback.

**Comment by lvanfretti** [comment]
@dietmarw I will close this issue, and we can discuss further  [using this issue](https://github.com/itesla/ipsl/issues/4).
